<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

1. Subsetting refers to selecting something from a list or array.
1. Indexing means to select one element from a list or array.
1. Slicing means to select a range of elements in a list or array.
1. Masking is used to return a collection of elements from an array that meets the condition of the mask. The syntax is as follows: array[mask]

# Exercise 2

In [ ]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

numbers_only_array = np_array_2d[:, 0].astype(int) #isolate the first element of each array in np_array_2d, which are the numbers. Then, convert them to type integer from type string
mask = (numbers_only_array % 2) == 1 #create a mask for numbers that give a remainder of 1 when divided by 2(odd numbers)
letters_of_odd_num = np_array_2d[mask][:, 1]
print(letters_of_odd_num)


['A' 'C' 'E' 'G' 'I']
[['1' 'A']
 ['3' 'C']
 ['2' 'B']
 ['4' 'D']
 ['5' 'E']
 ['7' 'G']
 ['6' 'F']
 ['8' 'H']
 ['10' 'J']
 ['9' 'I']]


# Exercise 3

In [21]:
import numpy as np

array_2d = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

mask_below_50 = (array_2d < 50) * -1 #boolean values can be stored as 1 and 0. all value below 50 will have value of 1 in the mask
mask_above_50 = (array_2d > 50) #all values above 50 will be stored as 1
mask_equal_50 = array_2d * 0
result = mask_below_50 + mask_above_50 + mask_equal_50
print(result)

#compare then assign values

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


In [22]:
import numpy as np

array_2d = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

array_2d[array_2d < 50] = -1 #Do this step first because if I convert numbers above 50 to 1 first then they will count as <50 later and be converted to -1
array_2d[array_2d > 50] = 1
array_2d[array_2d == 50] = 0
print(array_2d)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
