<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

1. Subsetting refers to selecting something from a list or array.
1. Indexing means to select one element from a list or array.
1. Slicing means to select a range of elements in a list or array.
1. Masking is used to return a collection of elements from an array that meets the condition of the mask. The syntax is as follows: array[mask]

# Exercise 2

In [8]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

numbers_only_array = np_array_2d[:, 0].astype(int)
mask = (numbers_only_array % 2) == 1
letters_of_odd_num = np_array_2d[mask][:, 1]
print(letters_of_odd_num)


['A' 'C' 'E' 'G' 'I']


# Exercise 3

In [ ]:
import numpy as np

array_2d = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

mask_below_50 = (array_2d < 50).astype(int) * -1
mask_above_50 = (array_2d > 50).astype(int) 
mask_equal_50 = array_2d * 0
result = mask_below_50 + mask_above_50 + mask_equal_50
print(result)

#compare then assign values

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
-1
